// <auto-generated />
using System;
using MessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backned.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220215923_SingleMealSchedule")]
    partial class SingleMealSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChargedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTime")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("WasTaken")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date", "MealTime")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("MessManagement.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillMonth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserMealIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MessManagement.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MessManagement.Models.Mess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Messes");
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MessId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessManagement.Models.UserBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastBillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBalances");
                });

            modelBuilder.Entity("MessManagement.Models.UserMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dishes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasEaten")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTime")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("TotalBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserMeals");
                });

            modelBuilder.Entity("MessManagement.Models.WeekSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WeekSchedules");
                });

            modelBuilder.Entity("MessManagement.Models.Meal", b =>
                {
                    b.OwnsOne("MessManagement.Models.MealImage", "Image", b1 =>
                        {
                            b1.Property<int>("MealId")
                                .HasColumnType("integer");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MealId");

                            b1.ToTable("Meals");

                            b1.WithOwner()
                                .HasForeignKey("MealId");
                        });

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.OwnsOne("MessManagement.Models.ProfilePicture", "ProfilePicture", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("ProfilePicture")
                        .IsRequired();
                });

            modelBuilder.Entity("MessManagement.Models.WeekSchedule", b =>
                {
                    b.OwnsOne("MessManagement.Models.DaySchedule", "Friday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Monday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Saturday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Sunday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Thursday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Tuesday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.OwnsOne("MessManagement.Models.DaySchedule", "Wednesday", b1 =>
                        {
                            b1.Property<int>("WeekScheduleId")
                                .HasColumnType("integer");

                            b1.Property<int?>("EveningMealId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MorningMealId")
                                .HasColumnType("integer");

                            b1.HasKey("WeekScheduleId");

                            b1.ToTable("WeekSchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeekScheduleId");
                        });

                    b.Navigation("Friday")
                        .IsRequired();

                    b.Navigation("Monday")
                        .IsRequired();

                    b.Navigation("Saturday")
                        .IsRequired();

                    b.Navigation("Sunday")
                        .IsRequired();

                    b.Navigation("Thursday")
                        .IsRequired();

                    b.Navigation("Tuesday")
                        .IsRequired();

                    b.Navigation("Wednesday")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
